### ISSUE TITLE
Support an implicit many-to-many relations

### ISSUE THREAD

**Issue by yubrot** [samchon/prisma-markdown#6]
This is a good tool. Thank you!
As of now, it seems that [implicit m-n-relations](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#implicit-many-to-many-relations) are not illustrated, it would be good to support it as well.
```prisma
model Post {
  id         Int        @id @default(autoincrement())
  title      String
  categories Category[]
}

model Category {
  id    Int    @id @default(autoincrement())
  name  String
  posts Post[]
}
```
![image](https://github.com/samchon/prisma-markdown/assets/10561571/71bd140a-2339-453d-8bdc-bc08097d2b81)

**Comment by samchon** [comment]
Oh, I hadn't known that prisma starts supporing implicit M: N relationship.

By the way, generated schema is extremely ugly. I'll support this feature, but recommend not to use it.

![image](https://github.com/samchon/prisma-markdown/assets/13158709/0c97cb2d-17e5-4193-ba0b-9eb37d323d3d)

**Comment by samchon** [comment]
Upgrade to `v1.0.3`, then be supported.

**Comment by yubrot** [comment]
Thank you for the quick response!

**Comment by samchon** [comment]
@yubrot Upgrade to `v1.0.4`.

Previous version has a bug that misunderstanding self-recursive 1: N relationship as implicit M: N relationship.

Therefore, previous version may draw non-existing table and diagram for that.
